#include<stdio.h>

typedef int (*funcp) (int x);

/*
	FUNCAO QUE RECEBE COMO PARAMETRO UM ARQUIVO COM FUNCOES NA LINGUAGEM SBF
	 E AS TRADUZ PARA LINGUAGEM DE MAQUINA, RETORNANDO ESSE CODIGO TRADUZIDO EM code
	 E O ENDERECO DA ULTIMA FUNCAO EM entry
 */
void geracod (FILE *f, void **code, funcp *entry);

/*
	FUNCAO PARA DESALOCAR O ESPACO RESERVADO PARA O CODIGO DE MAQUINA
 */
void liberacod (void *p);
